name = "solana"
version = "0.1.0"
description = "Web-Scale Blockchain for fast, secure, scalable, decentralized apps and marketplaces."
homepage = "https://solana.com"
image = "solanalabs/solana:stable"
