name = "solana"
version = "0.1.0"
homepage = "https://solana.com"
description = "Web-Scale Blockchain for fast, secure, scalable, decentralized apps and marketplaces."
repository = "https://github.com/solana-labs/solana.git"
documentation = "https://docs.solana.com"
license = "Apache-2.0"

keywords = ["blockchain", "solana", "network", "runtime", "web3", "decentralized"]
categories = ["blockchain"]

[deploy]
image = "index.docker.io/solanalabs/solana:stable"
