name = "prometheus"
version = "0.1.0"
homepage = "https://prometheus.io/"
description = "The Prometheus monitoring system and time series database."
repository = "https://github.com/prometheus/prometheus"
documentation = "https://prometheus.io/docs/introduction/overview/"
license = "Apache-2.0"

keywords = ["monitoring", "time-series", "metrics", "alerting", "prometheus", "graphing"]
categories = ["observability"]

[deploy]
image = "prom/prometheus:latest"
