name = "pulsar"
version = "0.1.0"
homepage = "https://pulsar.apache.org/"
description = "Apache Pulsar is an open-source, distributed messaging and streaming platform built for the cloud."
repository = "https://github.com/apache/pulsar/"
documentation = "https://pulsar.apache.org/docs/3.0.x/"
license = "Apache-2.0"

keywords = ["message-queue", "messaging", "cloud-native", "streaming", "distributed-systems"]
categories = ["message-queue"]

[deploy]
image = "apachepulsar/pulsar:3.0.2"
command = "bin/pulsar standalone"
