name = "starrocks"
version = "0.1.0"
homepage = "https://www.starrocks.io"
description = "An Open-Source, High-Performance Analytical Database"
repository = "https://github.com/StarRocks/starrocks"
documentation = "https://docs.starrocks.io/"
license = "Apache-2.0"

keywords = ["database", "analytics", "sql", "olap"]
categories = ["database"]

[deploy]
image = "starrocks/allin1-ubuntu:2.5-latest"
